#!/usr/bin/env python3
"""
Write beepy-nav/tests/gpx/asok.gpx, and the C literal view_nav.c carries.

The geometry is not invented: it is mockup.py's load_osm(), which builds the
route out of the actual carriageway geometry in osm-asok.json -- north up
Ratchadaphisek/Asok to the Sukhumvit junction, right, then left into the first
soi past it (DESIGN.md 6.5). That is the composition nav-turn-osm.png shows,
and it is the one the tile pack's demo page has to reproduce, so it is taken
from the same function rather than transcribed by eye.

    cd beepy-nav && python3 tests/gpx/gen_asok.py            # rewrite the GPX
    cd beepy-nav && python3 tests/gpx/gen_asok.py --c        # the C array too

The GPX is COMMITTED -- osm-asok.json is 450 KB and is excluded from the
device rsync, so nothing downstream of it may need the extract at build time.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

M_PER_DEG_LAT = 110540.0
M_PER_DEG_LON = 111320.0

HEAD = """<?xml version="1.0" encoding="UTF-8"?>
<!-- The Asok / Sukhumvit route of DESIGN.md 6.5, generated by
     tests/gpx/gen_asok.py from osm-asok.json's real carriageway geometry:
     north up Ratchadaphisek, right at the junction, left into Soi Sukhumvit
     23. It is the route tools/mktiles.py cuts the demo tile pack around. -->
<gpx version="1.1" creator="beepy-nav gen_asok.py">
  <metadata><name>Asok</name></metadata>
  <trk>
    <name>Asok</name>
    <trkseg>
"""
TAIL = """    </trkseg>
  </trk>
</gpx>
"""


def main():
    import mockup
    _, route = mockup.load_osm()
    _, _, met = mockup.osm_frame()
    pts = route["pts"]

    # mockup.py's frame is referenced to the junction; invert it back to
    # lat/lon so the GPX is real coordinates and mktiles.py can project it
    # with route.c's rule (reference = the FIRST point).
    fr = mockup.osm_frame()
    ways, name, m = fr
    # osm_frame() does not expose its own lat0/lon0, so recover them from a
    # point whose metres are known: met() is affine and met(p) of the junction
    # point is (0, 0) by construction.
    lat0 = lon0 = None
    for w in ways:
        for p in w["geometry"]:
            e, n = m(p)
            if abs(e) < 1e-9 and abs(n) < 1e-9:
                lat0, lon0 = p["lat"], p["lon"]
    if lat0 is None:
        raise SystemExit("gen_asok: could not recover the frame origin")
    ke = M_PER_DEG_LON * math.cos(math.radians(lat0))

    ll = [(lat0 + n / M_PER_DEG_LAT, lon0 + e / ke) for e, n in pts]

    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "asok.gpx"), "w") as f:
        f.write(HEAD)
        for la, lo in ll:
            f.write(f'      <trkpt lat="{la:.9f}" lon="{lo:.9f}"/>\n')
        f.write(TAIL)
    print(f"wrote asok.gpx: {len(ll)} points, turn_i {route['turn_i']}, "
          f"pin_i {route['pin_i']}")

    if "--c" in sys.argv:
        # The same points in the ROUTE frame -- referenced to the first point,
        # exactly as route.c's route_load() does -- which is the frame the
        # pack's own (lat0, lon0) lands on, so the two need no offset at all.
        rlat0, rlon0 = ll[0]
        rke = M_PER_DEG_LON * math.cos(math.radians(rlat0))
        print("\nstatic const double ASOK_ROUTE[] = {")
        for la, lo in ll:
            e = (lo - rlon0) * rke
            n = (la - rlat0) * M_PER_DEG_LAT
            print(f"    {e:.4f}, {n:.4f},")
        print("};")


if __name__ == "__main__":
    main()
