#!/usr/bin/env python3
"""
Generate beepy-nav/src/numerals.h: pre-rendered 1-bit glyph tables for the
big typeface numerals (DESIGN.md 5.2).

Sets emitted:
    NUM54    0-9 . -          cap 54 px   (NAV panel distance)
    NUM22    0-9 . -          cap 22 px   (overview strip, off-route, badges)
    UNITS22  M KM FT MI KM/H  cap 22 px   (unit words)

Each glyph is rendered exactly as mockup.py renders it -- the same face()
resolution chain (Arial Bold -> Helvetica -> DejaVu Sans Bold), drawn at 4x
and resolved with the same 50% threshold -- then cropped to its ink bbox.
Stored per glyph: ink width/height, (dx, dy) of the ink box relative to the
pen position at the CAP-TOP line, advance, and MSB-first packed rows.

The output is committed: regeneration needs this Mac's font stack, and the
device never runs Python. Treat diffs to numerals.h like code diffs.

Run from beepy-nav/ (mockup.py resolves ../gps-monitor relative paths):
    cd beepy-nav && python3 ../tools/gen_tables.py
"""

import subprocess
import sys

sys.path.insert(0, ".")
import mockup as m                                    # noqa: E402
from PIL import Image                                 # noqa: E402
import PIL                                            # noqa: E402

OUT = "src/numerals.h"
SETS = [
    ("NUM54", 54, list("0123456789.-")),
    ("NUM22", 22, list("0123456789.-")),
    ("UNITS22", 22, ["M", "KM", "FT", "MI", "KM/H"]),
]


def render_glyph(s, cap):
    """
    Rasterize `s` alone -> (bits, w, h, dy_natural, adv).

    The draw is shifted so the ink box lands on an exact 1x pixel, which is
    precisely what mockup.py's num() does. Without that shift the 4x box
    filter samples a different sub-pixel phase and every edge moves -- the
    first run of this generator differed from num() by ~30 px per glyph for
    exactly that reason.
    """
    c = m.Canvas()
    f = m.face(cap)
    origin = (40, 40)
    b = c.d.textbbox((0, 0), s, font=f)
    c.d.text((origin[0] * m.SS - b[0], origin[1] * m.SS - b[1]),
             s, font=f, fill=m.INK)
    adv = c.d.textlength(s, font=f) / m.SS
    img = m.resolve(c.img)                            # 400x240 1-bit
    px = img.load()
    # Ink starts at exactly `origin`; walk out its extent.
    x0, y0 = origin
    x1 = x0 + int(-(-(b[2] - b[0]) // m.SS)) + 1
    y1 = y0 + int(-(-(b[3] - b[1]) // m.SS)) + 1
    while x1 > x0 and all(px[x1 - 1, y] for y in range(y0, y1)):
        x1 -= 1
    while y1 > y0 and all(px[x, y1 - 1] for x in range(x0, x1)):
        y1 -= 1
    w, h = x1 - x0, y1 - y0
    rows = []
    for y in range(y0, y1):
        row, byte, nbit = [], 0, 0
        for x in range(x0, x1):
            byte = (byte << 1) | (0 if px[x, y] else 1)   # 1 = ink
            nbit += 1
            if nbit == 8:
                row.append(byte)
                byte, nbit = 0, 0
        if nbit:
            row.append(byte << (8 - nbit))
        rows.append(row)
    # b[1]/SS is the glyph's natural vertical offset below the pen line --
    # the caller turns it into an integer dy relative to the digit cap-top,
    # so '.' and '-' land at their type-correct heights when blitted.
    return rows, w, h, b[1] / m.SS, adv


def main():
    try:
        rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True).stdout.strip()
    except OSError:
        rev = "unknown"
    font_path = next(p for p in m.FACES
                     if __import__("os").path.exists(p))

    out = []
    o = out.append
    o("/* Generated by tools/gen_tables.py -- DO NOT EDIT BY HAND.")
    o(" *")
    o(f" * font: {font_path}")
    o(f" * PIL: {PIL.__version__}  python: {sys.version.split()[0]}")
    o(f" * generator commit: {rev}")
    o(" *")
    o(" * glyph_t.rows: h rows of (w+7)/8 bytes, MSB first, bit 1 = ink.")
    o(" * (dx, dy): ink-box offset from the pen at the cap-top line; digits")
    o(" * have dy == 0, '.' and '-' land at their type-correct heights.")
    o(" */")
    o("#ifndef NUMERALS_H")
    o("#define NUMERALS_H")
    o("")
    o("typedef struct {")
    o("    const char *tag;")
    o("    int w, h, dx, dy, adv;")
    o("    const unsigned char *rows;")
    o("} glyph_t;")
    o("")

    for set_name, cap, glyphs in SETS:
        # cap-top: digit '0''s natural offset is the reference line.
        _, _, _, cap_dy, _ = render_glyph("0", cap)
        entries = []
        for g in glyphs:
            rows, w, h, dy_nat, adv = render_glyph(g, cap)
            ident = (f"{set_name}_{g}" if g.isalnum()
                     else f"{set_name}_x{ord(g[0]):02x}")
            ident = ident.replace("/", "_")
            flat = [b for r in rows for b in r]
            o(f"static const unsigned char {ident}_bits[] = {{")
            for i in range(0, len(flat), 16):
                o("    " + ", ".join(f"0x{b:02x}" for b in flat[i:i+16]) + ",")
            o("};")
            entries.append((g, w, h, 0, round(dy_nat - cap_dy), adv, ident))
        o(f"static const glyph_t {set_name}[] = {{")
        for g, w, h, dx, dy, adv, ident in entries:
            o(f'    {{ "{g}", {w}, {h}, {dx}, {dy}, {round(adv)}, '
              f"{ident}_bits }},")
        o("};")
        o(f"enum {{ {set_name}_N = {len(entries)}, {set_name}_CAP = {cap} }};")
        o("")
    o("#endif /* NUMERALS_H */")

    import os
    os.makedirs("src", exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    size = os.path.getsize(OUT)
    print(f"wrote {OUT}: {size} bytes, "
          f"{sum(len(g) for _, _, g in SETS)} glyphs")


if __name__ == "__main__":
    main()
