#!/usr/bin/env python3
"""
Generate beepy-nav/src/labels.h: pre-rendered bitmaps for the few typeface
STRINGS the pages draw that are neither digits nor unit tags -- the
OFF-ROUTE panel's words. Companion to gen_tables.py: it imports that
module and reuses its render pipeline, so a label is rendered exactly as
mockup.py's PIL path renders the same string (4x supersample, 50%
threshold, ink-box crop) and stored in the same glyph_t format.

Whole words rather than a letter alphabet: only three strings exist, the
inter-letter kerning stays exactly what the typeface says, and the table
stays tiny.

Run from beepy-nav/ (as gen_tables.py is):
    cd beepy-nav && python3 ../tools/gen_labels.py
"""

import os
import sys

sys.path.insert(0, ".")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_tables as gt                               # noqa: E402

OUT = "src/labels.h"
# NOW is the countdown's last rung (DESIGN.md 1.1.1). It occupies the distance
# slot, so it is the same typeface as the digits it replaces -- at cap 36, the
# largest that fits the 128 px panel (54 would be 179 px wide).
LABELS = [("OFF", 24), ("ROUTE", 24), ("M AWAY", 20), ("NOW", 36)]


def ident_for(s):
    return "LABELS_" + "".join(ch if ch.isalnum() else "_" for ch in s)


def main():
    out = []
    o = out.append
    o("/* Generated by tools/gen_labels.py -- DO NOT EDIT BY HAND.")
    o(" *")
    o(" * Whole-string typeface bitmaps for the OFF-ROUTE panel words,")
    o(" * rendered through the same pipeline as numerals.h (see")
    o(" * tools/gen_tables.py). glyph_t comes from numerals.h.")
    o(" */")
    o("#ifndef LABELS_H")
    o("#define LABELS_H")
    o("")
    o('#include "numerals.h"')
    o("")
    entries = []
    for s, cap in LABELS:
        _, _, _, cap_dy, _ = gt.render_glyph("0", cap)
        rows, w, h, dy_nat, adv = gt.render_glyph(s, cap)
        ident = ident_for(s)
        flat = [b for r in rows for b in r]
        o(f"static const unsigned char {ident}_bits[] = {{")
        for i in range(0, len(flat), 16):
            o("    " + ", ".join(f"0x{b:02x}" for b in flat[i:i + 16]) + ",")
        o("};")
        entries.append((s, w, h, 0, round(dy_nat - cap_dy), round(adv), ident))
    o("static const glyph_t LABELS[] = {")
    for s, w, h, dx, dy, adv, ident in entries:
        o(f'    {{ "{s}", {w}, {h}, {dx}, {dy}, {adv}, {ident}_bits }},')
    o("};")
    o(f"enum {{ LABELS_N = {len(entries)} }};")
    o("")
    o("#endif /* LABELS_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {os.path.getsize(OUT)} bytes, {len(entries)} labels")


if __name__ == "__main__":
    main()
