#!/usr/bin/env python3
"""
Generate beepy-nav/src/query24.h: the FIND page's 24 px query typeface
(DESIGN.md 1.4, by the mechanism of 5.2).

    QUERY24   A-Z 0-9 space . / -     cap 24 px

DESIGN.md 1.4 sets the query in "24 px bold", and until M6 that was the one
string on any page still drawn by rasterizing a TrueType face live -- which
mockup.py can do on a Mac and the device cannot do at all. So the query joins
the numerals of 5.2: pre-rendered 1-bit glyphs, integer pen advances, the same
face resolution chain, generated by the same code as tools/gen_tables.py and
blitted by the same seg.c. Mockup and panel are then identical BY CONSTRUCTION
rather than by resemblance, which is what lets the FIND page into the design
gate at all.

40 glyphs at cap 24 is 2.4 KB of table, against 319 MB free.

Separate from numerals.h on purpose: regenerating that file would re-render the
NUM54/NUM22 digits through whatever PIL this Mac has today, and seven frozen
goldens hang off those exact bitmaps. A new header adds glyphs without touching
one of them.

Run from beepy-nav/ (mockup.py resolves ../gps-monitor by relative path):
    cd beepy-nav && python3 ../tools/gen_query.py
"""

import os
import subprocess
import sys

sys.path.insert(0, ".")
import mockup as m                                    # noqa: E402
import PIL                                            # noqa: E402

OUT = "src/query24.h"
CAP = 24
# A-Z and 0-9 are what the Beepy's keyboard puts in the query. Space is in the
# table with no ink at all -- it is an advance, and a query of two words needs
# it. The three punctuation marks are not typeable one-handed but DO occur in
# OSM names ("SOI SUKHUMVIT 49/16"), and a name echoed into the query line
# should not lose characters.
CHARS = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ./-")


def main():
    try:
        rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True).stdout.strip()
    except OSError:
        rev = "unknown"
    font_path = next(p for p in m.FACES if os.path.exists(p))

    # gen_tables.py's renderer, imported rather than copied: the two headers
    # must be produced by the same arithmetic or seg.c cannot blit both with
    # one code path.
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import gen_tables                                 # noqa: E402

    out = []
    o = out.append
    o("/* Generated by tools/gen_query.py -- DO NOT EDIT BY HAND.")
    o(" *")
    o(f" * font: {font_path}")
    o(f" * PIL: {PIL.__version__}  python: {sys.version.split()[0]}")
    o(f" * generator commit: {rev}")
    o(" *")
    o(" * The FIND page's 24 px query (DESIGN.md 1.4). glyph_t comes from")
    o(" * numerals.h, which seg.c includes first; the layout rules are 5.2's.")
    o(" */")
    o("#ifndef QUERY24_H")
    o("#define QUERY24_H")
    o("")

    _, _, _, cap_dy, _ = gen_tables.render_glyph("0", CAP)
    entries = []
    for ch in CHARS:
        rows, w, h, dy_nat, adv = gen_tables.render_glyph(ch, CAP)
        if ch.isalnum():
            ident = f"QUERY24_{ch}"
        else:
            ident = f"QUERY24_x{ord(ch):02x}"
        flat = [b for r in rows for b in r]
        if not flat:
            # Space: an advance and no ink. One byte so the array is not
            # zero-length (which C forbids); h == 0 means seg.c never reads it.
            flat = [0x00]
        o(f"static const unsigned char {ident}_bits[] = {{")
        for i in range(0, len(flat), 16):
            o("    " + ", ".join(f"0x{b:02x}" for b in flat[i:i + 16]) + ",")
        o("};")
        dy = 0 if h == 0 else round(dy_nat - cap_dy)
        tag = ch if ch != '"' else '\\"'
        entries.append((tag, w, h, 0, dy, round(adv), ident))
    o("static const glyph_t QUERY24[] = {")
    for tag, w, h, dx, dy, adv, ident in entries:
        o(f'    {{ "{tag}", {w}, {h}, {dx}, {dy}, {adv}, {ident}_bits }},')
    o("};")
    o(f"enum {{ QUERY24_N = {len(entries)}, QUERY24_CAP = {CAP} }};")
    o("")
    o("#endif /* QUERY24_H */")

    os.makedirs("src", exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {os.path.getsize(OUT)} bytes, {len(CHARS)} glyphs")


if __name__ == "__main__":
    main()
